### ISSUE TITLE
[Feature] Swipe customization

### ISSUE THREAD

**Issue by robsontenorio** [seivan/swipe-to-navigate#10]
Thanks for this extension!

Just saw #6 and I would say it would be really nice to be able:

- Customize swipe direction (reverse)
- Make it work with with 2 fingers. Currently works only with 3 fingers.

**Comment by seivan** [comment]
@robsontenorio Did you read the comments posted [here](https://github.com/seivan/swipe-to-navigate/issues/6#issuecomment-732020072)

**Comment by seivan** [comment]
Closing in favour of https://github.com/seivan/swipe-to-navigate/issues/6 as it was reopened by original author.
