### ISSUE TITLE
doesn't work on mac m1

### ISSUE THREAD

**Issue by Desync-o-tron** [seivan/swipe-to-navigate#13]
vs code version 1.58
macos 11.4 w/ m1

enabled monkey patch, nothing happened.

**Comment by moroz-slavomir** [comment]
Installed today on my mac. Doesn't work for me either. V1.58.2 arm64.

**Comment by megakrutak** [comment]
It doesn't work for me either on Mac M1

**Comment by seivan** [comment]
I don't have an M1 to test on, but I can try to dig into it if someone can test out extensions?

**Comment by megakrutak** [comment]
Yes, I can test

**Comment by seivan** [comment]
Tested today on a M1 and it worked with this version of VSCode. 
```
Version: 1.61.2
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T15:03:09.437Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.4.0
```
Can you dump your VSCode settings and a screenshot of your Swipe settings? 

Can you make sure your swipe settings are set to: 
<img width="339" alt="image" src="https://user-images.githubusercontent.com/55424/139227352-8d3ab112-1983-48e9-a3e3-419b2368ceb8.png">

**Comment by nathanloyer** [comment]
Doesn't work for me either. It used to, idk if it's an integration issue with newer versions of vscode or monkey patch. I feel like sometimes it starts working again and then later breaks.

Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z (3 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

**Comment by pinpontitit** [comment]
Doesnt work for me neither on macbook air M1, even aftter setting correctly.
But I guess the extension is no longer supported ?

**Comment by seivan** [comment]
> Doesn't work for me either. It used to, idk if it's an integration issue with newer versions of vscode or monkey patch. I feel like sometimes it starts working again and then later breaks.
> 
> Version: 1.63.2 (Universal) Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3 Date: 2021-12-15T09:37:28.172Z (3 wks ago) Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin x64 19.6.0

That's usually because the bootstrap has been replaced. Restarting with monkey patch would bring it back on again.
Currently investigating a thread on how to get around that.

**Comment by seivan** [comment]
> Doesnt work for me neither on macbook air M1, even aftter setting correctly. But I guess the extension is no longer supported ?

It was, but not anymore. I'm adding some new things.

**Comment by pinpontitit** [comment]
Thanks Mate, I look forward

**Comment by arturmakaranka** [comment]
m1 pro chip, latest version for VSCode - doesn't work

**Comment by seivan** [comment]
Closing in favour https://github.com/seivan/swipe-to-navigate/issues/18
This issue is more related to he hack that is monkey patching than the actual electron listener.
