### ISSUE TITLE
VSCode 1.71.0 - Swipe to Navigate stopped working after last update

### ISSUE THREAD

**Issue by caffeineflo** [seivan/swipe-to-navigate#15]
Hi!
First of all, this great plugin helps me keep my sanity while I'm outside of my comfort zone in VSCode - Unfortunately with the latest release of VSCode this plugin stopped working for me.

I believe my VSCode updated late last week and after the most recent update Swipe to Navigate stopped working. I've tested various settings, have uninstalled and reinstalled both Swipe To Navigate as well as Monkey Patch and reapplied the changes multiple times - neither of which worked.

I'm on a M1 MacBook Pro, here's my Code Version:

```
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:25.516Z (5 days ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

I don't see any error in the extension host logs or in the dev tools console fwiw, happy to provide more detailed logs if those help!

Thanks

**Comment by kevinboosten** [comment]
I've tried it in the latest Insiders version as well (to have a completely isolated version without any other extensions installed), unfortunately without success either :'( 

```
Version: 1.72.0-insider (Universal)
Commit: 0f2de31e4856886cdbf32f85488bc40f480fb38f
Date: 2022-09-07T05:19:31.123Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

```
Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

**Comment by yichuan1118** [comment]
```
Version: 1.73.0 (Universal)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:38:50.881Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```

same issue here

**Comment by hmijail** [comment]
Monkey Patch, which is used by Swipe toNavigate, is seemingly going away, so that might be the reason. https://github.com/iocave/monkey-patch/issues/55

**Comment by seivan** [comment]
@hmijail Correct, but won't need it now :) closed in favour of https://github.com/seivan/swipe-to-navigate/issues/18
