### ISSUE TITLE
Does anyone know any other similar extensions?

### ISSUE THREAD

**Issue by yalishanda42** [seivan/swipe-to-navigate#17]
I'd really love to have the swipe backwards/forwards gesture in VSCode (like I do in Xcode) but unfrotunately this one is not working (I guess due to MonkeyPatch being deprecated). :/

**Comment by seivan** [comment]
@yalishanda42 Yeah, we're not gonna need MonkeyPatch, I'm deprecating the extension and pushing it upstream.

**Comment by seivan** [comment]
Closing in favour https://github.com/seivan/swipe-to-navigate/issues/18
