### ISSUE TITLE
Not able to install in a docker-compose devenvironment.

### ISSUE THREAD

**Issue by ascheucher** [seivan/swipe-to-navigate#5]
What I did:
* Working on Mac OS X Mojave
* open VSC project with one Docker dev container and two others for Selenium web testing.
* installed Swipe To Navigate in the extension marketplace
* restarted as suggested 

Got following error message:
Monkey Patch failed: Error: ENOENT: no such file or directory, open '/root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/code/electron-browser/workbench/workbench.html'

**Comment by seivan** [comment]
@ascheucher Just to clarify, you're running VSCode within docker, or on your native environment over a project that is within docker?

**Comment by seivan** [comment]
@ascheucher The extension modifies your vscode, it will fail if it can't find it or have permission to modify it. 
Could you confirm that it exists at `'/root/.vscode-server/bin/d2e414d9e4239a252d1ab117bd7067f125afd80a/out/vs/code/electron-browser/workbench/workbench.html` in which case, I am guessing it's a permission issue? 

Either way, I am not sure how to proceed from here, feel free to reopen if you have more to add.
